version: '3.8'

services:
  roteador:
    image: alpine
    container_name: roteador
    command: sh -c "apk add --no-cache iptables && sleep infinity"
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.254
      rede_clientes:
        ipv4_address: 192.168.2.254
    cap_add:
      - NET_ADMIN

  dns:
    build: ./dns
    container_name: dns
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.2

  dhcp:
    build: ./dhcp
    container_name: dhcp
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.3
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./dhcp/leases:/var/lib/dhcp

  firewall:
    build: ./firewall
    container_name: firewall
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.4
    cap_add:
      - NET_ADMIN

  ldap:
    build: ./ldap
    container_name: ldap
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.5

  samba:
    build: ./samba
    container_name: samba
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.6

  ftp:
    build: ./ftp
    container_name: ftp
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.7

  web:
    build: ./web
    container_name: web
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.8

networks:
  rede_servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

  rede_clientes:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

