version: "3.3"

services:
  dns:
    build: ./dns
    container_name: dns-server
    networks:
      servidores:
        ipv4_address: 172.20.1.10
    volumes:
      - ./dns/named.conf.options:/etc/bind/named.conf.options:ro
      - ./dns/db.intranet.local:/etc/bind/db.intranet.local:ro
      - ./dns/db.172.20.1:/etc/bind/db.172.20.1:ro
      - ./dns/db.2.20.172:/etc/bind/db.2.20.172:ro
      - ./dns/named.conf.local:/etc/bind/named.conf.local:ro
    ports:
      - "10053:53/tcp"
      - "10053:53/udp"
    restart: unless-stopped

  dhcp:
    build: ./dhcp
    container_name: dhcp-server
    networks:
      servidores:
        ipv4_address: 172.20.1.12
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      - dhcp_data:/var/lib/dhcp

  ftp:
    build: ./ftp
    container_name: ftp-server
    networks:
      servidores:
        ipv4_address: 172.20.1.16
    volumes:
      - ./ftp/vsftpd.conf:/etc/vsftpd.conf:ro
    ports:
      - "2121:21"
    command: ["/usr/sbin/vsftpd", "-v", "/etc/vsftpd.conf"]
    restart: unless-stopped

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-server
    networks:
      servidores:
        ipv4_address: 172.20.1.18
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_DOMAIN: intranet.local
      LDAP_ADMIN: admin
      LDAP_PASSWORD: sua_senha_do_admin_aqui
      LDAP_BASE_DN: dc=intranet,dc=local
      LDAP_TLS: "true"  # Ajustado para string
      LDAP_TLS_CRT_CN: ldap.intranet.local
    volumes:
      - ldap_data:/var/lib/ldap
    restart: unless-stopped

  router:
    build: ./router
    container_name: router
    networks:
      servidores:
        ipv4_address: 172.20.1.7
      clientes:
        ipv4_address: 172.20.2.7
    privileged: true
    command: bash -c "ip route add 172.20.2.0/24 dev eth1 && sysctl -w net.ipv4.ip_forward=1 && /usr/sbin/dhcrelay -i eth1 172.20.1.12 & tail -f /dev/null"
    restart: unless-stopped

  web:
    build: ./web
    container_name: web-server
    networks:
      servidores:
        ipv4_address: 172.20.1.14
    volumes:
      - ./web/index.html:/var/www/html/index.html:ro
    ports:
      - "8080:80"
    restart: unless-stopped

  cliente:
    build: ./cliente
    container_name: cliente1
    networks:
      clientes: {}
    depends_on:
      - router
    command: sleep infinity
    restart: unless-stopped

networks:
  servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24

  clientes:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24

volumes:
  dhcp_data:
  ldap_data:

